# This file is automatically generated by E:\simulationcraft2\source_files\synchronize.py
# To change the list of source files, update the QT_ files and run E:\simulationcraft2\source_files\synchronize.py


 SOURCES += engine/sc_main.cpp